'use client'

import { useState } from 'react'
import { apiFetch } from '@/lib/api'

interface Member {
  id: string
  fullName?: string
  full_name?: string
  email: string
}

interface Expense {
  id: string
  description: string
  amount: number
  paidBy: string
  paid_by: string
  category: string
  createdAt: string
  created_at: string
}

interface Settlement {
  fromUserId: string
  toUserId: string
  fromUserName: string
  toUserName: string
  amount: number
}

interface Props {
  groupId: string
  groupName: string
  userId: string
  members: Member[]
}

export default function ExportPDF({ groupId, groupName, userId, members }: Props) {
  const [loading, setLoading] = useState(false)

  function getMemberName(memberId: string) {
    const member = members.find(m => m.id === memberId)
    return member?.fullName ?? member?.full_name ?? 'Unknown'
  }

  async function handleExport() {
    setLoading(true)

    try {
      const [expenses, settlements] = await Promise.all([
        apiFetch(`/groups/${groupId}/expenses`, userId),
        apiFetch(`/groups/${groupId}/settlements`, userId),
      ])

      const { jsPDF } = await import('jspdf')
      const doc = new jsPDF()

      const pageWidth = doc.internal.pageSize.getWidth()
      let y = 20

      // Title
      doc.setFontSize(20)
      doc.setFont('helvetica', 'bold')
      doc.text('SplitEasy', 20, y)

      y += 10
      doc.setFontSize(14)
      doc.setFont('helvetica', 'normal')
      doc.text(`Group: ${groupName}`, 20, y)

      y += 7
      doc.setFontSize(10)
      doc.setTextColor(120, 120, 120)
      doc.text(`Generated on ${new Date().toLocaleDateString('en-ZA', {
        day: 'numeric', month: 'long', year: 'numeric'
      })}`, 20, y)
      doc.setTextColor(0, 0, 0)

      y += 7
      doc.setDrawColor(200, 200, 200)
      doc.line(20, y, pageWidth - 20, y)

      // Members
      y += 10
      doc.setFontSize(12)
      doc.setFont('helvetica', 'bold')
      doc.text('Members', 20, y)
      y += 7
      doc.setFontSize(10)
      doc.setFont('helvetica', 'normal')
      members.forEach(member => {
        doc.text(`• ${member.fullName ?? member.full_name} (${member.email})`, 25, y)
        y += 6
      })

      y += 4
      doc.line(20, y, pageWidth - 20, y)

      // Expenses
      y += 10
      doc.setFontSize(12)
      doc.setFont('helvetica', 'bold')
      const totalSpent = expenses.reduce((sum: number, e: Expense) => sum + e.amount, 0)
      doc.text(`Expenses  —  Total: R${totalSpent.toFixed(2)}`, 20, y)
      y += 7

      doc.setFontSize(9)
      doc.setFont('helvetica', 'bold')
      doc.text('Description', 25, y)
      doc.text('Category', 100, y)
      doc.text('Paid by', 135, y)
      doc.text('Amount', 175, y)
      y += 5
      doc.setDrawColor(200, 200, 200)
      doc.line(20, y, pageWidth - 20, y)
      y += 5

      doc.setFont('helvetica', 'normal')
      expenses.forEach((expense: Expense) => {
        if (y > 270) {
          doc.addPage()
          y = 20
        }
        doc.text(expense.description.substring(0, 30), 25, y)
        doc.text(expense.category || 'Other', 100, y)
        doc.text(getMemberName(expense.paidBy ?? expense.paid_by).substring(0, 20), 135, y)
        doc.text(`R${expense.amount.toFixed(2)}`, 175, y)
        y += 6
      })

      y += 4
      doc.line(20, y, pageWidth - 20, y)

      // Settlement summary
      y += 10
      doc.setFontSize(12)
      doc.setFont('helvetica', 'bold')
      doc.text('Settlement Summary', 20, y)
      y += 7

      doc.setFontSize(10)
      doc.setFont('helvetica', 'normal')

      if (settlements.length === 0) {
        doc.text('All settled up! No outstanding debts.', 25, y)
        y += 6
      } else {
        settlements.forEach((s: Settlement) => {
          if (y > 270) {
            doc.addPage()
            y = 20
          }
          const fromName = s.fromUserId === userId ? 'You' : s.fromUserName
          const toName = s.toUserId === userId ? 'you' : s.toUserName
          doc.text(`• ${fromName} owe${s.fromUserId === userId ? '' : 's'} ${toName}: R${s.amount.toFixed(2)}`, 25, y)
          y += 6
        })
      }

      // Footer
      y += 10
      doc.setFontSize(8)
      doc.setTextColor(150, 150, 150)
      doc.text('Generated by SplitEasy — spliteasy-alpha.vercel.app', 20, y)

      doc.save(`${groupName.replace(/\s+/g, '_')}_expenses.pdf`)
    } catch (err) {
      alert('Failed to generate PDF. Please try again.')
    } finally {
      setLoading(false)
    }
  }

  return (
    <button
      onClick={handleExport}
      disabled={loading}
      className="text-sm text-slate-500 hover:text-slate-700 font-medium transition-colors disabled:opacity-50 flex items-center gap-1.5"
    >
      {loading ? 'Generating...' : '↓ Export PDF'}
    </button>
  )
}
